

[logging]
version=1
[logging.formatters]
[logging.formatters.brief]
format = "%(message)s"

[logging.formatters.precise]
format = "%(asctime)s %(levelname)-8s %(name)-15s %(message)s"
datefmt = "%Y-%m-%d %H:%M:%S"

[logging.handlers]
[logging.handlers.console]
class = "logging.StreamHandler"
formatter = "precise"
stream = "ext://sys.stdout"

[logging.handlers.file]
class = "logging.handlers.RotatingFileHandler"
formatter = "precise"
filename = "log/log"
maxBytes = 2048
backupCount = 3

[logging.loggers]
[logging.loggers.root]
level = "DEBUG"
handlers = ["console", "file"]

